"""Populates the DB with starter scenarios and country lists if tables are empty."""
from database import get_conn, init_db, add_country_to_list, get_country_list

SEED_EU_COUNTRIES = [
    ("AT", "Austria"), ("BE", "Belgium"), ("BG", "Bulgaria"), ("CY", "Cyprus"),
    ("CZ", "Czech Republic"), ("DE", "Germany"), ("DK", "Denmark"), ("EE", "Estonia"),
    ("ES", "Spain"), ("FI", "Finland"), ("FR", "France"), ("GR", "Greece"),
    ("HR", "Croatia"), ("HU", "Hungary"), ("IE", "Ireland"), ("IT", "Italy"),
    ("LT", "Lithuania"), ("LU", "Luxembourg"), ("LV", "Latvia"), ("MT", "Malta"),
    ("NL", "Netherlands"), ("PL", "Poland"), ("PT", "Portugal"), ("RO", "Romania"),
    ("SE", "Sweden"), ("SI", "Slovenia"), ("SK", "Slovakia"),
]

SEED_NON_EU_COUNTRIES = [
    ("AE", "United Arab Emirates"), ("AU", "Australia"), ("BR", "Brazil"),
    ("CA", "Canada"), ("CH", "Switzerland"), ("CN", "China"), ("GB", "United Kingdom"),
    ("HK", "Hong Kong"), ("IN", "India"), ("JP", "Japan"), ("KR", "South Korea"),
    ("MX", "Mexico"), ("NO", "Norway"), ("NZ", "New Zealand"), ("RU", "Russia"),
    ("SA", "Saudi Arabia"), ("SG", "Singapore"), ("TH", "Thailand"), ("TR", "Turkey"),
    ("TW", "Taiwan"), ("UA", "Ukraine"), ("US", "United States"), ("ZA", "South Africa"),
]

SEED_SCENARIOS = [
    # ── Germany ─────────────────────────────────────────────────────────────
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.19,
        "supplier_location": "Domestic",
        "item_nature": "Goods",
        "vat_treatment": "STANDARD",
        "scenario_name": "DE — Domestic goods, 19% VAT",
        "default_code": "HY01",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.07,
        "supplier_location": "Domestic",
        "item_nature": "Goods",
        "vat_treatment": "STANDARD",
        "scenario_name": "DE — Domestic goods, 7% VAT (reduced rate)",
        "default_code": "HY02",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.19,
        "supplier_location": "Domestic",
        "item_nature": "Services",
        "vat_treatment": "STANDARD",
        "scenario_name": "DE — Domestic services, 19% VAT",
        "default_code": "HY03",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.07,
        "supplier_location": "Domestic",
        "item_nature": "Services",
        "vat_treatment": "STANDARD",
        "scenario_name": "DE — Domestic services, 7% VAT (reduced rate)",
        "default_code": "HY04",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.0,
        "supplier_location": "EU",
        "item_nature": "Goods",
        "vat_treatment": "RC_INTRA_EU",
        "scenario_name": "DE — Intra-EU goods acquisition, reverse charge (Art. 44)",
        "default_code": "HY05",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.0,
        "supplier_location": "EU",
        "item_nature": "Services",
        "vat_treatment": "RC_INTRA_EU",
        "scenario_name": "DE — Intra-EU services, reverse charge §3a",
        "default_code": "HY06",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.0,
        "supplier_location": "NonEU",
        "item_nature": "Services",
        "vat_treatment": "RC_NONEU_SERVICES",
        "scenario_name": "DE — Non-EU services, reverse charge §13b",
        "default_code": "HY07",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.0,
        "supplier_location": "Domestic",
        "item_nature": "Services",
        "vat_treatment": "RC_DOMESTIC_§13b",
        "scenario_name": "DE — Domestic reverse charge §13b (construction, scrap, etc.)",
        "default_code": "HY08",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.0,
        "supplier_location": "NonEU",
        "item_nature": "Goods",
        "vat_treatment": "EXEMPT_EXPORT",
        "scenario_name": "DE — Import from non-EU (customs-cleared, no VAT on invoice)",
        "default_code": "HY09",
        "notes": "VAT handled at customs / fiscal representative",
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.0,
        "supplier_location": "Domestic",
        "item_nature": "Services",
        "vat_treatment": "KLEINUNTERNEHMER",
        "scenario_name": "DE — Kleinunternehmer supplier §19 UStG (no VAT charged)",
        "default_code": "HY10",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.0,
        "supplier_location": "Domestic",
        "item_nature": "Services",
        "vat_treatment": "EXEMPT_§4Nr14",
        "scenario_name": "DE — Healthcare / medical services §4 Nr.14 UStG",
        "default_code": "HY11",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.0,
        "supplier_location": "Domestic",
        "item_nature": "Services",
        "vat_treatment": "EXEMPT_§4Nr8",
        "scenario_name": "DE — Banking / financial services §4 Nr.8 UStG",
        "default_code": "HY12",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "InsuranceTax",
        "tax_rate": 0.19,
        "supplier_location": "Domestic",
        "item_nature": "Services",
        "vat_treatment": "NON_VAT",
        "scenario_name": "DE — Versicherungsteuer (Insurance premium tax, not VAT)",
        "default_code": "HY13",
        "notes": "Tax type is Versicherungsteuer, not Umsatzsteuer",
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.0,
        "supplier_location": "Domestic",
        "item_nature": "Services",
        "vat_treatment": "EXEMPT_§4Nr11b",
        "scenario_name": "DE — Postal universal service §4 Nr.11b UStG",
        "default_code": "HY14",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.0,
        "supplier_location": "Domestic",
        "item_nature": "Mixed",
        "vat_treatment": "EXEMPT_§4Nr12",
        "scenario_name": "DE — Residential rent §4 Nr.12 UStG",
        "default_code": "HY15",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.0,
        "supplier_location": "Domestic",
        "item_nature": "Services",
        "vat_treatment": "EXEMPT_§4Nr21",
        "scenario_name": "DE — Education services §4 Nr.21 UStG",
        "default_code": "HY16",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "CreditNote",
        "tax_type": "VAT",
        "tax_rate": 0.19,
        "supplier_location": "Domestic",
        "item_nature": "Goods",
        "vat_treatment": "STANDARD",
        "scenario_name": "DE — Credit note, domestic goods 19% VAT",
        "default_code": "HY17",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "CreditNote",
        "tax_type": "VAT",
        "tax_rate": 0.19,
        "supplier_location": "Domestic",
        "item_nature": "Services",
        "vat_treatment": "STANDARD",
        "scenario_name": "DE — Credit note, domestic services 19% VAT",
        "default_code": "HY18",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Payroll",
        "tax_type": "NonTax",
        "tax_rate": None,
        "supplier_location": "N/A",
        "item_nature": "N/A",
        "vat_treatment": "NON_VAT",
        "scenario_name": "DE — Payroll posting (no VAT)",
        "default_code": "HY19",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Compensation",
        "tax_type": "NonTax",
        "tax_rate": None,
        "supplier_location": "N/A",
        "item_nature": "N/A",
        "vat_treatment": "NON_VAT",
        "scenario_name": "DE — Compensation / damages payment (no VAT)",
        "default_code": "HY20",
        "notes": None,
    },
    {
        "recipient_country": "DE",
        "transaction_type": "Donation",
        "tax_type": "NonTax",
        "tax_rate": None,
        "supplier_location": "N/A",
        "item_nature": "N/A",
        "vat_treatment": "NON_VAT",
        "scenario_name": "DE — Donation (no VAT)",
        "default_code": "HY21",
        "notes": None,
    },
    # ── France ───────────────────────────────────────────────────────────────
    {
        "recipient_country": "FR",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.20,
        "supplier_location": "Domestic",
        "item_nature": "Goods",
        "vat_treatment": "STANDARD",
        "scenario_name": "FR — Domestic goods, 20% TVA",
        "default_code": "HY22",
        "notes": None,
    },
    {
        "recipient_country": "FR",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.10,
        "supplier_location": "Domestic",
        "item_nature": "Goods",
        "vat_treatment": "STANDARD",
        "scenario_name": "FR — Domestic goods, 10% TVA (intermediate rate)",
        "default_code": "HY23",
        "notes": None,
    },
    {
        "recipient_country": "FR",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.055,
        "supplier_location": "Domestic",
        "item_nature": "Goods",
        "vat_treatment": "STANDARD",
        "scenario_name": "FR — Domestic goods, 5.5% TVA (reduced rate)",
        "default_code": "HY24",
        "notes": None,
    },
    {
        "recipient_country": "FR",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.20,
        "supplier_location": "Domestic",
        "item_nature": "Services",
        "vat_treatment": "STANDARD",
        "scenario_name": "FR — Domestic services, 20% TVA",
        "default_code": "HY25",
        "notes": None,
    },
    {
        "recipient_country": "FR",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.0,
        "supplier_location": "EU",
        "item_nature": "Goods",
        "vat_treatment": "RC_INTRA_EU",
        "scenario_name": "FR — Intra-EU goods acquisition, reverse charge",
        "default_code": "HY26",
        "notes": None,
    },
    {
        "recipient_country": "FR",
        "transaction_type": "Invoice",
        "tax_type": "VAT",
        "tax_rate": 0.0,
        "supplier_location": "EU",
        "item_nature": "Services",
        "vat_treatment": "RC_INTRA_EU",
        "scenario_name": "FR — Intra-EU services, reverse charge",
        "default_code": "HY27",
        "notes": None,
    },
]


def seed():
    init_db()

    # Seed scenarios
    with get_conn() as conn:
        count = conn.execute("SELECT COUNT(*) FROM scenarios").fetchone()[0]
    if count == 0:
        with get_conn() as conn:
            for s in SEED_SCENARIOS:
                cols = ", ".join(s.keys())
                placeholders = ", ".join("?" * len(s))
                conn.execute(f"INSERT INTO scenarios ({cols}) VALUES ({placeholders})", list(s.values()))
        print(f"Seeded {len(SEED_SCENARIOS)} scenarios.")
    else:
        print(f"DB already has {count} scenarios — skipping scenario seed.")

    # Seed EU country list
    if not get_country_list("EU"):
        for code, name in SEED_EU_COUNTRIES:
            add_country_to_list("EU", code, name)
        print(f"Seeded {len(SEED_EU_COUNTRIES)} EU countries.")

    # Seed NonEU country list
    if not get_country_list("NonEU"):
        for code, name in SEED_NON_EU_COUNTRIES:
            add_country_to_list("NonEU", code, name)
        print(f"Seeded {len(SEED_NON_EU_COUNTRIES)} NonEU countries.")


if __name__ == "__main__":
    seed()
